apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort  # NodePort 타입으로 변경!
  selector:
    app: nginx-deployment
  ports:
    - protocol: TCP
      port: 8000       # 서비스 내부 포트
      targetPort: 8000 # 컨테이너 포트
      nodePort: 30080  # 외부에서 접근할 포트 (30000~32767 사이 숫자)
